version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: multiroledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  backend:
    build: .
    container_name: springboot-multiRoleAuth
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/multiroledb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: toor
      JWT_SECRET: 748596123asd5416fghjklqwer125165tyuiop4984zxcvbnm
      JWT_EXPIRATION: 900000
      SERVER_PORT: 8081

    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  pgdata:
